brew "gcc"
brew "tldr"
brew "trash"

cask "arc"
cask "karabiner-elements"
cask "notion-calendar"
cask "notion"
cask "raycast"
cask "rectangle"
cask "scroll-reverser"
cask "shottr"
cask "slack"
cask "spotify"
cask "visual-studio-code"