brew "fzf"
brew "lazygit"
brew "tmux"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "brave-browser"
cask "ghostty"
cask "homerow"
cask "karabiner-elements"
cask "rectangle"
