#!/usr/bin/env sh

spacebar -m config spacing_left         25
spacebar -m config spacing_right        25
spacebar -m config text_font            "JetBrainsMono Nerd Font:Regular:12.0"
spacebar -m config icon_font            "JetBrainsMono Nerd Font:Regular:15.0"
spacebar -m config clock_icon_color     0xff5ea7e4
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config clock_format         "%a %d %b %l:%M%p"
